services:
  craiyon-bot:
    build: .
    environment:
      TDLIB_COMMIT_HASH: d321984b75fccdb76239529e8aadcf7f80b0e35a
      USER_AGENT:
      TELEGRAM_TOKEN:
      API_ID:
      API_HASH:
      DB_ENCRYPTION_KEY:
      FAL_API_KEY:
      STABLEHORDE_TOKEN:
      STABLEHORDE_CLIENT:
      MAKERSUITE_API_KEY:
      GROQ_API_KEY:
    volumes:
      - craiyon-bot:/data

volumes:
  craiyon-bot:
